export const GET_ARTICLES_PENDING = 'GET_ARTICLES_PENDING'
export const GET_ARTICLE_BY_ID_PENDING = 'GET_ARTICLE_BY_ID_PENDING'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLE_BY_ID_SUCCESS = 'GET_ARTICLE_BY_ID_SUCCESS'
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED'
export const GET_ARTICLE_BY_ID_FAILED = 'GET_ARTICLE_BY_ID_FAILED'

export const EDIT_ARTICLE_PENDING = 'EDIT_ARTICLE_PENDING'
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS'
export const EDIT_ARTICLE_FAILED = 'EDIT_ARTICLE_FAILED'

export const CREATE_ARTICLE_PENDING = 'CREATE_ARTICLE_PENDING'
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS'
export const CREATE_ARTICLE_FAILED = 'CREATE_ARTICLE_FAILED'

export const DELETE_ARTICLE_PENDING = 'DELETE_ARTICLE_PENDING'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLES_FAILED'
