export const GET_ARTICLES_PENDING = 'GET_ARTICLES_PENDING'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED'

export const EDIT_ARTICLE = 'EDIT_ARTICLE'
export const CREATE_ARTICLE = 'CREATE_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
